
apiVersion: v1
kind: Service
metadata:
  name: xld-svc
  labels:
    app: xld
spec:
  type: LoadBalancer
  ports:
    - name: xld-https-svc
      port: 4517
      targetPort: xld-https
      protocol: TCP
  selector:
    app: xld